server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name __DOMAIN__;

    ssl_certificate     /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    resolver 127.0.0.11 valid=10s;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        set $wp_upstream wordpress:9000;
        fastcgi_pass $wp_upstream;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location = /adminer { return 301 /adminer/; }
    location /adminer/ {
        set $adminer_upstream adminer:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/adminer/index.php;
        fastcgi_pass $adminer_upstream;
    }

    location = /site { return 301 /site/; }
    location /site/ {
        set $static_upstream static:80;
        rewrite ^/site/(.*)$ /$1 break;
        proxy_pass http://$static_upstream;
    }
}
